### ISSUE TITLE
rake fingerbank:update fails

### ISSUE THREAD

**Issue by JonPe** [julsemaan/fingerbank_client#1]
When executing "rake fingerbank:update", I get below error.  I think here its trying to download the sqlite database from fingerbank.

ubuntu@ubuntu:~/fingerbank/fingerbank_client-master/lib/fingerbank_client$ rake fingerbank:update
(in /home/ubuntu/fingerbank/fingerbank_client-master)
rake aborted!
Zlib::BufError: buffer error
/home/ubuntu/fingerbank/fingerbank_client-master/lib/fingerbank_client/upstream.rb:11:in `update'
/home/ubuntu/fingerbank/fingerbank_client-master/lib/tasks/fingerbank_client_tasks.rake:12:in `block (2 levels) in <top (required)>'
Tasks: TOP => fingerbank:update

I have downloaded the packaged.sqlite3 database from fingerbank. Is it possible to use the downloaded database as local and continue ?

**Comment by julsemaan** [comment]
The database is now pretty enormous and seems to exceed the buffer for uncompressing it

It should probably use a disk buffer instead of a RAM buffer

Unfortunately, the fingerbank SQLite3 DB is being deprecated which means even if this gets fixed, it will be useless in a few months which is why I'll be closing this
